"""initial schema

Revision ID: 21b179020fc3
Revises:
Create Date: 2026-07-10 22:54:21.297755

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21b179020fc3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_code", sa.String(), nullable=False),
        # แก้ไฟล์ auto-generate ตรงนี้ได้เพราะ schema นี้ยังไม่เคย apply ที่ไหนจริง —
        # teacher_token เพิ่มเข้า model ภายใน stack เดียวกัน (PR #27) ก่อน merge
        sa.Column("teacher_token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_room_code"), ["room_code"], unique=True)

    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_players_player_id"), ["player_id"], unique=True)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("respawn_count", sa.Integer(), nullable=False),
        sa.Column("environmental_score", sa.Float(), nullable=True),
        sa.Column("mission_score", sa.Float(), nullable=True),
        sa.Column("quiz_score", sa.Float(), nullable=True),
        sa.Column("hake_gain", sa.Float(), nullable=True),
        sa.Column("heat_controlled_pct", sa.Float(), nullable=True),
        sa.Column("events_json", sa.String(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "run_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_player_id"), ["player_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_run_id"))
        batch_op.drop_index(batch_op.f("ix_runs_player_id"))

    op.drop_table("runs")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_players_player_id"))

    op.drop_table("players")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_room_code"))

    op.drop_table("sessions")
    # ### end Alembic commands ###
