"""add stealth assessment fields

Revision ID: 2bebaee29c94
Revises: 59904533c2e0
Create Date: 2026-07-13 23:49:56.849040

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bebaee29c94"
down_revision = "59904533c2e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("net_impact_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("cognitive_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("rank", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("balance_version", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_column("balance_version")
        batch_op.drop_column("rank")
        batch_op.drop_column("cognitive_score")
        batch_op.drop_column("net_impact_score")

    # ### end Alembic commands ###
