"""fix run_id index to be non-unique matching declared session+run_id constraint

Revision ID: 59904533c2e0
Revises: 21b179020fc3
Create Date: 2026-07-13 23:48:10.957610

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "59904533c2e0"
down_revision = "21b179020fc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite batch mode ต้องการชื่อ constraint เสมอ (autogenerate ให้ None มา ต้องเติมเอง —
    # ดู https://alembic.sqlalchemy.org/en/latest/batch.html) ตั้งชื่อตาม convention
    # uq_<table>_<cols> ให้ตรงกับ UniqueConstraint("session_id", "run_id") ใน models.py
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_run_id"))
        batch_op.create_index(batch_op.f("ix_runs_run_id"), ["run_id"], unique=False)
        batch_op.create_unique_constraint("uq_runs_session_id_run_id", ["session_id", "run_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_runs_session_id_run_id", type_="unique")
        batch_op.drop_index(batch_op.f("ix_runs_run_id"))
        batch_op.create_index(batch_op.f("ix_runs_run_id"), ["run_id"], unique=1)

    # ### end Alembic commands ###
